<a href="https://colab.research.google.com/github/danieldosadi/AulaGit/blob/main/aula_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Atividade Quero duas tabelas
# 1 - Filtrando por Pais/Country exemplo "Germany"
# 2 - Filtrando por
#    País/Country ordenado por pontos/point score

# Opcional retornar o número de linhas em cada tabela

In [12]:
# Passo 1 - Importar pandas
import pandas as pd

# Passo 2 - Ler arquivo

dados = pd.read_csv('Soccer_Football Clubs Ranking.csv')
dados

,ranking,club name,country,point score,1 year change,previous point scored,symbol change
0,88,1. FC Köln,Germany,1633,105,1545,+
1,74,1. FC Union Berlin,Germany,1655,5,1654,+
2,780,12 de Octubre de Itaugua,Paraguay,1377,70,1388,-
3,268,1º de Agosto,Angola,1513,13,1516,-
4,2525,1º de Maio,Angola,1218,22,1218,-
...,...,...,...,...,...,...,...
2807,316,Zrinjski Mostar,Bosnia and Herzegovina,1488,127,1449,+
2808,1387,Zulia,Venezuela,1304,123,1318,-
2809,1187,Zulte Waregem,Belgium,1326,423,1377,-
2810,2389,Zumunta,Niger,1231,30,1231,-
2811,325,Zürich,Switzerland,1484,424,1381,+

In [13]:
# Passo 3 - Converter em DataFrame
data_frame = pd.DataFrame(dados)

In [20]:
# Passo 4 - Criar Filtro
filtro_por_country = data_frame['country'] == ''
dados_filtrados = data_frame[filtro_por_country].copy()

In [18]:
dados_filtrados.sort_values(by='point score', inplace=True)
dados_filtrados

<ipython-input-18-93aad70e6a66>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_filtrados.sort_values(by='point score', inplace=True)

,ranking,club name,country,point score,1 year change,previous point scored,symbol change
1075,2718,FK Leotar,Bosnia and Herzegovina,1176,2,1177,-
18,2705,AC LALA FC,Venezuela,1180,280,1230,-
2694,2662,Vitez,Bosnia and Herzegovina,1193,13,1193,-
1195,2653,Gradina Srebrenik,Bosnia and Herzegovina,1196,14,1196,-
1056,2637,FK Drina Zvornik,Bosnia and Herzegovina,1200,14,1200,-
...,...,...,...,...,...,...,...
849,49,Eintracht Frankfurt,Germany,1697,25,1769,-
383,27,Bayer Leverkusen,Germany,1773,17,1714,+
448,21,Borussia Dortmund,Germany,1792,4,1821,-
2122,15,RB Leipzig,Germany,1826,3,1804,+
384,1,Bayern München,Germany,2045,0,2057,-